# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 759b47d396f226eb9114c6cda1ce105fdfe912c095bf2383661b88e90edfefda4cd22f037b81f128398de94a54142c4146d842fd22078c9e62c770efa59f1244

test:
  secret_key_base: 42e3a6d99be49c9afeed37106daa22525e2ae9c260a9ca38e8ce88c933279711bdb25fe6fc4cc70518d6c30e32ee884e6322058e4d5227ac9b6353572f762243

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
